open-feature/flagd

.gitignore
Makefile
pkg/eval/json_evaluator.go

Remove the schema read operation in favor of the `embed` directive.

Embed schema with directive

---

Dockerfile

Add flag schema layer

---

go.mod
go.sum

Update to new version of json-logic to fix substr bug.
See: https://github.com/diegoholiveira/jsonlogic/issues/52

Update json logic

---

.gitignore
README.md
cmd/start.go
config/samples/example_flags_secondary.json
pkg/eval/json_evaluator.go
pkg/eval/json_evaluator_model.go
pkg/eval/json_evaluator_test.go
pkg/runtime/runtime.go

JSON merge function for multiple files 

---

pkg/sync/http_sync.go

Fix response body close

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/documentation.yaml
.github/ISSUE_TEMPLATE/feature.yaml

A label called `Needs Triage` will be added to all new issues.

Proposal for an issue template

---

.github/ISSUE_TEMPLATE/feature.yaml

Add note about OFEP to the feature template

---

cmd/start.go
pkg/eval/json_evaluator.go
pkg/eval/tests/json_evaluator_test.go
pkg/runtime/runtime.go
pkg/service/grpc_service.go
pkg/service/grpc_service_test.go
pkg/service/http_service.go
pkg/sync/filepath_sync.go
pkg/sync/http_sync.go

Signed-off-by: Alex Jones <alexsimonjones@gmail.com>

split out loggers

---

.github/ISSUE_TEMPLATE/feature.yaml

Fix grammatical issue in the feature template

---

pkg/service/grpc_service.go

[issue](https://github.com/open-feature/flagd/issues/103)
Follows similar pattern to the http service.
Signed-off-by: James-Milligan <james@omnant.co.uk>

[FEATURE] TLS for grpc service

---

README.md
cmd/start.go

Signed-off-by: Alex Jones <alexsimonjones@gmail.com>

updated the default port for next release

---

Makefile

Fixes date to `yyyy-MM-dd'T'HH:mm:ss` standard

fix: date inconsistency

---

pkg/runtime/from_config.go

Signed-off-by: Alex Jones <alexsimonjones@gmail.com>

fix: bug in the logger setup

---

go.mod
go.sum

Signed-off-by: Skye Gill <gill.skye95@gmail.com>

fix: upgrade package containing vulnerability

---

pkg/service/connect_service.go

Signed-off-by: James-Milligan <james@omnant.co.uk>

fix: updated tcp listener

---

pkg/sync/kubernetes/featureflagconfiguration/clientset.go
pkg/sync/kubernetes/kubernetes_sync.go

Signed-off-by: Skye Gill <gill.skye95@gmail.com>

feat: only fire modify event when FeatureFlagConfiguration Generation field has changed

---

CONTRIBUTING.md
README.md

Adds contributing section to the docs.

chore: contributing section for the docs

---

.github/workflows/build.yaml
.github/workflows/publish-benchmark.yaml
.github/workflows/release-please.yaml
go.mod

Signed-off-by: James Milligan <james@omnant.co.uk>
- bumps go version to 1.19

chore: bump go version

---

Makefile
docs/usage/evaluation_examples.md
pkg/runtime/from_config.go

Improves examples and messaging around sync URI errors.
Closes: https://github.com/open-feature/flagd/issues/251

fix: improve invalid sync URI errror msg

---

docs/usage/getting_started.md

- Add instructions for installing with homebrew
Resolves #285 
```sh
brew update
brew search flagd
```
this should output the following
```sh
❯ brew search flagd
==> Formulae
flagd                                                    flac
```
then install with 
```sh
brew install flagd
```

docs: Update docs

---

cmd/start.go

Signed-off-by: jamesmilligan <james@omnant.co.uk>
- fixes incorrect default on deprecation warning, preventing warning log when the flag is not used

fix: deprecation warning fix

---

.github/workflows/release-please.yaml

- feat(release): add homebrew-core bump step
Fixes #306 
Two TODOs with this PR:
- create a new release (it has been used by many other projects)

ci(release): add homebrew-core bump step

---

.github/workflows/build.yaml

ci: skip build action when only docs change

---

cmd/start.go

fix: update outdated doc link in deprecation warning

---

systemd/flagd.service

fix: Update flagd systemd config to use URI

---

.github/workflows/release-please.yaml

- adds explicit dependency on release please
- ensures a homebrew update PR is created

ci: adds explicit dependency on release please

---

pkg/runtime/runtime.go

Signed-off-by: James Milligan <james@omnant.co.uk>
- buffers channel on startup to prevent blocking in linked issue
https://github.com/open-feature/flagd/issues/356

fix: fix unbuffered channel blocking goroutine 

---

pkg/sync/http/http_sync_test.go
pkg/sync/http/mock/http.go

Signed-off-by: James Milligan <james@omnant.co.uk>
- commits mockgen deltas
- updates tests for generated interfaces

test: commit mockgen deltas, update tests for generated interfaces

---

release-please-config.json

- Adds additional sections to the release notes.
Now with more emojis 🔥 💥 💯

chore: add additional sections to the release notes

---

pkg/eval/fractional_evaluation.go

- removes non-error error log from parseFractionalEvaluationData

fix: remove non-error error log from parseFractionalEvaluationData 

---

docs/README.md
docs/configuration/flag_configuration_merging.md

- adds documentation for merge events + resyncs
https://github.com/open-feature/flagd/issues/452

docs: configuration merge docs

---

release-please-config.json

- fix paths for release pelase

ci: fix paths for release please

---

release-please-config.json

- fix release paths for release please

ci: fix release paths for release please

---

config/deployments/kube-flagd-proxy/deployment.yaml
kube-flagd-proxy/README.md
release-please-config.json

- replaces flagd version tags with `:latest`

ci: remove release please config for flagd versions

---

core/pkg/runtime/from_config.go
core/pkg/runtime/runtime.go
core/pkg/service/flag-evaluation/connect_service.go
core/pkg/service/flag-evaluation/connect_service_test.go
core/pkg/service/iservice.go

chore: refactor service configuration objects

---

Makefile

chore: init workspace before building the project

---

mkdocs.yml
netlify.toml
pyproject.toml

- Adds social graph plugins to https://flagd.dev for nice link previews
Closes #820

docs: add social graphs plugin

---

.github/workflows/build.yaml
netlify.toml

- ignore doc publishing if nothing has changed
Fixes #810

ci: ignore doc publishing if nothing has changed

---

mkdocs.yml
web-docs/concepts/syncs.md
web-docs/reference/sync-configuration.md

* add concepts/sync and reference/sync-config pages

syncs, sync config

---

mkdocs.yml
web-docs/architecture.md
web-docs/deployment.md

* adds high level arch doc
* removes rp-versioning from `/deployment`

add basic arch doc

---

.gitmodules
.markdownlint-cli2.yaml
Makefile
mkdocs.yml
web-docs/faq.md
web-docs/reference/providers.md
web-docs/reference/specifications/in-process-providers.md
web-docs/reference/specifications/protos.md
web-docs/reference/specifications/rpc-providers.md

- adds providers page
- adds rpc-providers spec
- adds automated .proto docs

chore: add protoc, rpc provider doc, FAQ

---

docs/index.md
docs/reference/flag-definitions.md
docs/troubleshooting.md

* fixes some links
* adds bit about required version for `fractional`
* adds bit about multiple fs events, symlinks
* adds blurb about HTTP2 being blocked in some environments
Fixes: https://github.com/open-feature/flagd/issues/894
Fixes: https://github.com/open-feature/flagd/issues/479
Fixes: https://github.com/open-feature/flagd/issues/362

chore: various doc fixes

---

docs/reference/specifications/in-process-providers.md

- fix link to provider ecosystem page

docs: fix link to provider ecosystem page

---

docs/assets/extra.css
docs/troubleshooting.md
mkdocs.yml

* use same colors as openfeature.dev
* use switch theme toggle
* improve searchability of troubleshooting topic

chore: minor style tweaks

---

README.md

- Update readme links
Fixed links that were affected by the updates to the documentation.
Thank you, Prithviraj for reporting the issue.
relates to: https://github.com/open-feature/flagd/pull/973

docs: fix links on the readme

---

.golangci.yml
flagd/cmd/start.go

Fixes a few lint issues, directly, and by ignoring some submodules.

chore: fix lint errors

---

test/integration/evaluation_test.go
test/integration/go.mod
test/integration/json_evaluator_test.go

Update test dependencies to go-sdk 1.9.0

chore: update to go-sdk 1.9.0

---

config/samples/example_flags.flagd.json
config/samples/example_flags.flagd.yaml

Fixes flagd flag configuration examples.

chore: fix examples

---

docs/schema/v0/targeting.json

Updates schema to include https://github.com/open-feature/flagd-schemas/pull/131.
Fixes: https://github.com/open-feature/flagd/issues/1205
@austindrenski I imagine this is cached quite heavily by IDEs, etc. Not sure how long it will take to clear.
Preview link: https://deploy-preview-1215--polite-licorice-3db33c.netlify.app/schema/v0/targeting.json

docs: json schema update json/json-schema-v0.2.1

---

docs/concepts/syncs.md

see title.
mainly for this: https://github.com/open-feature/flagd-schemas/pull/134

chore: update schemas submodule for new json

---

docs/concepts/syncs.md

- updates documentation [typo](docs/concepts/syncs.md)

docs: Typo in syncs.md

---

core/pkg/evaluator/ievaluator.go
core/pkg/evaluator/json.go
core/pkg/store/flags.go
flagd/pkg/service/flag-evaluation/connect_service.go
flagd/pkg/service/flag-sync/sync-multiplexer.go

Refactor the flagd evaluator such that storage and evaluation logic are isolated. This allows us to plug any storage layer to the same evaluation logic, which could be valuable in the long run

chore: refactor evaluation core

---

core/pkg/evaluator/fractional.go
core/pkg/evaluator/fractional_test.go

Fixes https://github.com/open-feature/flagd/issues/1285

fix: missing/nil custom variables in fractional operator

---

docs/schema/v0/flags.json
docs/schema/v0/targeting.json

See title, and: 
https://github.com/open-feature/flagd-schemas/compare/json/json-schema-v0.2.4...json/json-schema-v0.2.5
https://github.com/open-feature/flagd-schemas/compare/json/json-schema-v0.2.3...json/json-schema-v0.2.4

fix: public schema update - fix unary op shorthand

---

renovate.json

Renovate constraints to Go 1.21

chore: fix renovate by setting correct renovate constrant

---

docs/schema/v0/flags.json
docs/schema/v0/targeting.json

chore: update public schema

---

docs/reference/specifications/proposal/rfc-grpc-custom-name-resolver.md

gRPC custom resolver rfc proposal doc update

docs: update gRPC custom resolver rfc proposal

---

core/pkg/evaluator/ievaluator.go
core/pkg/evaluator/json.go
core/pkg/evaluator/json_test.go
core/pkg/evaluator/mock/ievaluator.go
core/pkg/store/store.go
core/pkg/store/store_test.go
flagd/pkg/runtime/runtime.go

depends: #1792 for fixing build issues

feat!: cleanup evaluator interface
