open-feature/flagd

Makefile, pkg/sync/filepath_sync.go
Closes: https://github.com/open-feature/flagd/issues/42
@AlexsJones I found this issue which seems to have to do with the way K8s exposes configmaps when treated as volumes. The file is actually a symlink which is moved when the configmap is changed. This fires the remove event, which removes our watcher.
The solution seems to be to simply add the watcher back. This resolves the issue in my local cluster. @beeme1mr will confirm on his GKE cluster as well.
=> Restore watcher on remove

README.md
The curl command in the readme does not work on mac because it was not between quotes.
I have added the quotes to the README.md.
=> Readme CURL for mac

.github/workflows/build-oci.yaml
This is a temporary stop-gap to not run the trivy scan in PRs from forks, for now, since attempting a push from a fork causes a 403... Once the issue with the trivy action described [here](https://github.com/open-feature/flagd/pull/46) is fixed, we can change the build to do tarball scanning instead of scanning published images.
Closes: https://github.com/open-feature/flagd/issues/52
=> Disable pushing in forks

.github/workflows/build-oci.yaml, .github/workflows/code-checks.yaml, .gitignore, .golangci.yml, .pre-commit-config.yaml, Makefile, cmd/root.go, cmd/start.go, pkg/eval/ievaluator.go, pkg/eval/json_evaluator.go, pkg/eval/json_evaluator.model.go, pkg/runtime/runtime.go, pkg/service/http_service.go, pkg/service/iservice.go, pkg/sync/filepath_sync.go, pkg/sync/http_sync.go, pkg/sync/inotify.go, pkg/sync/isync.go
This pull request adds the support of `golangci-lint` which is a pretty standard linter for golang.
It will help to have a uniform way of writing go code in the repository.
I have also fixed all the issue that were raised by the linters.
The only one I have ignore is the one related to the hashing solution because I guess you have used `sha1` for a reason.
`golangci-lint` will also be run with github action.
There is also a `pre-commit` configuration to be used with https://pre-commit.com/ that will run `golangci-lint` and `gofumpt` at each commit.
Note that you have to install the pre-commit hook with the command `pre-commit install` to have this feature.
=> Add linters + pre-commit

.gitignore, Makefile
Just a small change here to install the linter bin via `go install` to the `GOPATH` instead of piping curl to the shell, which always makes me nervous.
=> go install linter

.github/workflows/build-push-oci.yaml, .github/workflows/build-scan-oci.yaml
This PR does trivy scanning with a local image instead of from a pushed image.
It also removes the scanning in main, because if this is merged nothing that hasn't been scanned should get that far.
=> Fix CI in PRs from forks, scan local image

pkg/service/grpc_service.go, pkg/service/grpc_service_test.go
Removed the SetEval method. Moved unit tests into package to allow for field access without setter function.
Signed-off-by: James-Milligan <james@omnant.co.uk>
=> removed setter for GRPCService eval field

pkg/eval/ievaluator.go, pkg/eval/json_evaluator.go, pkg/eval/json_evaluator_model.go, pkg/service/http_service.go
- Replaced `interface{}` with `any` (go 1.18)
- Changed variable name (`bytes` -> `data`) due to lint warning about collision with imported package name
- Re-use the evaluate logic to reduce code duplication in resolveX functions
BTW, saw we are not handling errors "the go way" (defining hard coded strings instead of typed errors)
Didn't tackle it within this PR but would like to hear if there is any specific reason I'm missing of choosing this option.
=> JSON evaluator using generics

.github/workflows/release.yaml
The latest release failed because it wasn't updated after the introduction of Buf. This PR should fix the issue.
https://github.com/open-feature/flagd/runs/7471890158?check_suite_focus=true
=> ci: Update release process to use buf

Makefile
This is a known bug in docker with multi-arch images, therefore we can drop out loading for now.
=> chore: fixing multi-arch build failure

README.md, docs/http_int_response.md, pkg/eval/fractional_evaluation_test.go, pkg/eval/json_evaluator.go, pkg/eval/json_evaluator_test.go, pkg/model/reason.go, pkg/service/grpc_service_test.go
Todd: This particular "reason" never made it into the spec, and only the node sdk implements it. I think it's value is minimal. I struggle a bit to find a good differentiation between DEFAULT and STATIC .
I propose removing this and replacing all instances of it with DEFAULT. If you guys think there's significant value in it though, we can make a spec change... I just think the ROI is low at this point.
=> refactor: Static reason type removal

cmd/start.go, pkg/runtime/start.go
Signed-off-by: Alex Jones <alexsimonjones@gmail.com>
https://github.com/open-feature/flagd/issues/169
=> fix: bubbles up unclean error exits

pkg/sync/kubernetes/kubernetes_sync.go
Signed-off-by: jamesmilligan <james@omnant.co.uk>
- fixes api version comparison
Version check was failing in kube sync.
CRD APIVersion = `core.openfeature.dev/v1alpha1`
v1alpha1.GroupVersion.Version = `v1alpha1`
replaced with a constructed group version: `fmt.Sprintf("%s/%s", v1alpha1.GroupVersion.Group, v1alpha1.GroupVersion.Version)`
=> fix: ApiVersion check fix

docs/caching.md, pkg/eval/json_evaluator.go, pkg/eval/json_evaluator_test.go, pkg/model/reason.go
Resurrected the STATIC flag reason. Documented the caching strategy.
Fixes #223
=> feat: Resurrected the STATIC flag reason. Documented the caching strategy.

pkg/service/connect_service.go
Changed eventing configuration mutex to rwmutex and added missing lock.
Fixes #219
=> fix: changed eventing configuration mutex to rwmutex and added missing lock

pkg/eval/json_evaluator_model.go
Added omitempty to the json tags of the `targeting` field in the `Flag` structure.
Fixes #246
=> fix: omitempty targeting field in Flag structure

pkg/eval/ievaluator.go, pkg/eval/json_evaluator.go, pkg/eval/json_evaluator_model.go, pkg/eval/json_evaluator_test.go, pkg/eval/mock/ievaluator.go, pkg/runtime/runtime.go
Consolidates configuration change events into a singular event (avoid superfluous bulk emissions).
Existing `configuration_change` event listeners will need to update their handling to consume the singular events.
Fixes #238
=> feat!: consolidated configuration change events into one event

pkg/sync/file/filepath_sync.go
Looks like during a refactor, we accidentally removed the "meat" of the remove handler.
In K8S, we never get write events, just remove. It's necessary to send the data for these as well.
Also extracted some duplicated code into a func.
=> fix: send datasync on remove fs events

.github/workflows/release-please.yaml, .goreleaser.yaml
Fixes #329 
Adding SBOM generation through go releaser. SBOM is generated per archive (see image for reference).
Along with the PR, changing deprecated archive naming [1]
Install goreleaser [2] and run following command tog get artefacts & sbom generates in local dist folder 
`goreleaser release --skip-publish --skip-validate  --rm-dist`
[1] - https://goreleaser.com/deprecations/#archivesreplacements
[2] - https://goreleaser.com/install/
=> chore: add sbom generation for releases

pkg/sync/file/filepath_sync.go
- Uses event.Has func for file change notification handling (instead of direct comparison). This is the correct approach as [expressed directly in fsnotify's code](https://github.com/fsnotify/fsnotify/blob/main/fsnotify.go#L39).
Fixes #313
=> fix: use event.Has func for file change notification handling (increased stability across OS)

.github/workflows/release-please.yaml
fixes #328
Introduce image signing for flagd. Signature is pushed to OCR repository and public key will get added to release artefacts under the name `publicKey.pub` (referred through variable PUBLIC_KEY_FILE in GH action)
**NOTE** - Require COSIGN_PRIVATE_KEY & COSIGN_PASSWORD secrets to be created. And decide how to expose public key
=> feat: flagd image signing

.github/workflows/release-please.yaml
- Adds a `download-url` to the Homebrew release action
Fixes #345 
The bump homebrew formula action takes an optional download url. By setting this value to a git-based URL, the action should update the tag and reversion.
https://github.com/mislav/bump-homebrew-formula-action#how-it-works
=> ci: set homebrew download URL

pkg/eval/fractional_evaluation_test.go, pkg/eval/json_evaluator.go, pkg/eval/json_evaluator_model.go, pkg/eval/json_evaluator_model_test.go, pkg/eval/json_evaluator_test.go
- Introduces RWMutex on flag state to prevent concurrent read/write of map.
Fixes #368
=> fix: introduced RWMutex to flag state to prevent concurrent r/w of map

pkg/service/connect_service.go
- Reinstate setting of ResolveObject's reason
Discovered as [integration tests PR](https://github.com/open-feature/flagd/pull/312) started failing. In future this kind of thing will be picked up as a pipeline failure (all the more reason to get to the bottom of the snyk security issue).
=> fix: set ResolveObject reason

CODEOWNERS
@Kavindu-Dodan has contributed multiple significant changes and proposals to flagd:
- multiple refactors: https://github.com/open-feature/flagd/pull/291, https://github.com/open-feature/flagd/pull/307
- ci/security improvements: https://github.com/open-feature/flagd/pull/338, https://github.com/open-feature/flagd/pull/337
- architectural proposals (some of which got some attention from outside parties!): https://github.com/open-feature/ofep/pull/45, https://github.com/open-feature/schemas/pull/78, https://github.com/open-feature/flagd/issues/249#issuecomment-1413590567
- load testing: https://github.com/open-feature/flagd/pull/225
- documentation improvements
For these reasons, I believe he should be made a CODEOWNER in this repository.
NOTE: before this is merged, @Kavindu-Dodan should …
=> chore: add @kavindu-dodan to CODEOWNERS

pkg/service/connect_service.go, pkg/service/connect_service_test.go, pkg/service/connect_service_types.go
- Reduces duplicated code in Resolve... funcs
Fixes #385 
Tested against integration tests.
=> refactor: simplify connect Resolve... funcs

pkg/service/connect_service.go
Fixes error handling of Serve/ServeTLS being deferred until flagd shutdown.
If an error occurred from one of these functions, it'd be ignored until shutdown.
=> fix: error handling of Serve/ServeTLS funcs

pkg/sync/http/http_sync.go
In the `TestSimpleSync` test we are asserting that `hs.Cron.AddFunc` and `hs.Cron.Start` are called by the time the `dataSync` is sent. This is a race, because these methods are actually called after the first send. I get failures here ~25% of the time (seems like @skyerus does too).
This changes things to add the handler and start the cron _before_ the first send, which makes things deterministic.
=> fix: fix race in http sync test

pkg/sync/file/filepath_sync_test.go
Newly added tests showed flakiness - this is due to missing initial fetch handling.
This PR improves tests only.
=> chore: fix race condition on init read

.github/workflows/release-please.yaml
Attach release image sbom to release artefacts. Right now, sbom is generated and stored with release action
=> chore: attach image sbom to release artefacts

.github/workflows/build.yaml, go.mod, go.sum
- Disables caching in CI (due to slow file I/O in github actions)
=> chore: disable caching tests in CI

cmd/start.go
- adds version to flagd startup message
Fixes #428
Running flagd from main branch:
... 
2023-02-23T17:44:37.503-0300    info    file/filepath_sync.go:32        Starting filepath sync notifier {"component": "sync", "sync": "filepath"}
2023-02-23T17:44:37.503-0300    info    service/connect_service.go:110  metrics listening at 8014       {"component": "service"}
...
Running flagd from this PR branch:
... 
2023-02-23T17:47:26.504-0300    info    cmd/start.go:97 flagd version: dev (15ef000), built at: 2023-02-23T17:47:20Z   {"component": "start"}
2023-02-23T17:47:26.504-0300    info    file/filepath_sync.go:32        Starting filepath sync notifier {"component": "sync", "sync": "filepath"}
...
=> feat: Add version to startup message

pkg/store/flags.go
- adds logging describing merge events, specifically when overwrites / deletes do not take place
https://github.com/open-feature/flagd/issues/453
=> feat: add debug logging for merge behaviour 

docs/other_resources/high_level_architecture.md, pkg/runtime/from_config.go, pkg/sync/file/filepath_sync_test.go, pkg/sync/grpc/grpc_sync.go, pkg/sync/grpc/grpc_sync_test.go, pkg/sync/http/http_sync.go, pkg/sync/http/http_sync_test.go
The current readiness state can be changed because of an underlying sync provider error. This seems to be incorrect as **not ready state** make flagd to not receive traffic through K8s services [1]
For example, if HTTP endpoint-backed sync provider get an error, the current logic set readiness to `false`. Similarly, if grpc connectivity is lost for grpc provider, readiness goes to `false` state till connection establishment completes. 
This PR fix this behavior by setting the ready state **once only** per sync provider. This means if there is at least a single successful sync, sync provider sets its readiness to `true`.
Going further, we might need to decide if we need better readiness state handling. 
[1] - https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readin …
=> fix: set readiness once only

go.mod, go.sum, pkg/runtime/from_config.go, pkg/sync/kubernetes/kubernetes_sync.go, pkg/sync/kubernetes/kubernetes_sync_test.go
- Refactor the code to make it easier to inject the K8s clients
- Add unit tests 
Fixes #460
=> chore: refactoring and improve coverage for K8s Sync

.github/workflows/release-please.yaml
Fixes container signing release step [1]. This step was missing the registry login step, hence signature push failed. 
[1] - https://github.com/open-feature/flagd/actions/runs/4357163255/jobs/7616231967
=> fix: add registry login

README.md, docs/usage/getting_started.md
- remove snap from the docs
Fixes #489 
I left the Snap configuration and Release Please configuration. That should make it easy to readd when the release process is automated.
=> docs: Remove Snap badge

.github/workflows/release-please.yaml
Re-enable the brew formula version bump. No changes are needed as we have all the necessary outputs, unchanged from the refactoring efforts.
=> chore: enable brew formula version bump

docs/other_resources/high_level_architecture.md
I am not sure why, but docusaurus does not like unclosed `<img>` tags. It will render an error, and the page can not be rendered.
- adds this new feature
Fixes #1234523
=> docs: ensure proper rendering with docusaurus

docs/usage/getting_started.md
- bump minimum go version to 1.19 in the binary install instructions
- update the URL in the binary install instructions
=> docs: update go binary install instructions

Makefile, core/pkg/eval/json_evaluator.go, core/pkg/runtime/runtime.go, core/pkg/service/flag-evaluation/connect_service.go, core/pkg/service/flag-evaluation/flag_evaluator.go, core/pkg/service/middleware/http_metrics.go, core/pkg/service/middleware/http_metrics_test.go, core/pkg/sync-store/sync_store.go, core/pkg/sync-store/sync_store_test.go, core/pkg/sync/file/filepath_sync.go, core/pkg/sync/grpc/credentials/builder.go, core/pkg/sync/grpc/grpc_sync.go, core/pkg/sync/grpc/grpc_sync_test.go, core/pkg/sync/http/http_sync.go, core/pkg/sync/kubernetes/kubernetes_sync.go, core/pkg/sync/kubernetes/kubernetes_sync_test.go
Fix lint check & adds lint fixes for existing lint failures (reason for 16 file changes)
See this example [1], linting was failing silently as we rely on a `foreach` loop. 
Solution credits - https://stackoverflow.com/a/22214424/3197055  
[1] - https://github.com/open-feature/flagd/actions/runs/4471193065/jobs/7855746534#step:5:640
=> fix: fixing silent lint failures

core/pkg/runtime/from_config.go, core/pkg/runtime/from_config_test.go, core/pkg/runtime/runtime.go, core/pkg/sync/isync.go, flagd/cmd/start.go
No logic changes - Pure refactoring[1] to untangle startup argument-based configurations from runtime.
Consider the simple sequence diagram below, 
```mermaid
sequenceDiagram
participant start
participant from_config
participant runtime
start-->>from_config: ParseSyncProviderURIs()
start-->>from_config: ParseSources()
start-->>from_config: FromConfig()
Note left of from_config: This parse & build the runtime.
from_config-->>start: Runtime
Note left of from_config: Runtime structure is self-contained & <br/> does not rely on the startup configuration
start-->>runtime: rt.Start()
loop Run
runtime->>runtime: flagd runtime
end
```
The core idea was to isolate startup configuration & get rid of the unwanted `Config` [2] structure parsing to the `Runtime` layer. 
This change 
- Helps to isolate …
=> chore: refactor configuration handling for startup

core/pkg/runtime/from_config.go, core/pkg/sync-store/sync_store.go
- fixes nil pointer deference bug with grpc sync
- exports constructors, this code was duplicated in the sync store
Fixes #1234523
```
go run flagd/main.go start --debug --sources '[{"uri":"grpc://localhost:8013","provider":"grpc","selector":"file:./config/samples/example_flags.json"}]'
```
resulted in 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x1047af4e8]
goroutine 1 [running]:
github.com/open-feature/flagd/core/pkg/sync/grpc.(*Sync).Init(0x140002671f0, {0x10582c6b0, 0x14000687450})
```
credential builder was not being set in the constructor
=> fix: nil pointer fix + export constructors

.github/workflows/publish-benchmark.yaml
- adds workspace initialization
Fixes #496
=> fix: init workspace before running scheduled benchmark tests

.github/workflows/release-please.yaml
- adds a base `release-type` as required by [Release Please](https://github.com/google-github-actions/release-please-action/blob/main/action.yml#L20-L22)
- update homebrew commit message to not include the flagd prefix
Homebrew uses the first line of the commit message as the PR title and the rest of the message as the PR body. Without a body, Homebrew will flag the PR as invalid.
Addresses: https://github.com/Homebrew/homebrew-core/pull/127098#issuecomment-1490624290
=> ci: improve homebrew release process

README.md, core/pkg/sync/file/filepath_sync_test.go, docs/usage/evaluation_examples.md
- fixes unit tests that failed on windows machines
- clarifies usage of flagd on a windows machine
https://github.com/open-feature/flagd/issues/630
The learning from this pr were:
1.  Always prefer using the go test suite tempdir instead of relying on os library to allocate and delete test folders, this simplifies code and avoids os-specific issues
2.  Make sure to always close file pointers, since leaving dangling ones tends to cause access errors in Windows aka error file already open. 
3.  When running via docker one must make sure that the file is in the same filesystem where the docker container runs than the watcher will work. AKA on Windows it is good as long as everything comes from WSL filesystem
=> chore: add instructions for windows and fix failing unit tests

.github/workflows/release-please.yaml
Fixes https://github.com/open-feature/flagd/issues/581 & https://github.com/open-feature/flagd/issues/639
**Third-party license artifacts https://github.com/open-feature/flagd/issues/581**
This PR improved release builds to add `<module>-third-party-license.tar.gz` to release artifacts. This artifact contains third-party licenses extracted using https://github.com/google/go-licenses.
This is an attempt to credit our dependencies and be license compliant (ex:- retaining copyright notices) where possible. 
Note that, the go-license tool emits error if it fails to identify licenses (ex:- for non-go codes/internal deps). This breaks the build (as it writes to stderr) and the workaround was to use `continue-on-error: true`. Unfortunately, GH Actions do not provide any better alternative and …
=> chore: adding licenses to release archives and provide zip archive for windows

core/pkg/service/sync/handler.go, core/pkg/service/sync/server.go, core/pkg/sync-store/interface.go, flagd-proxy/cmd/start.go
- decouples the sync store from sync server startup, allowing for alternative sync store implementations to be introduced
=> refactor: introduce isyncstore interface

core/pkg/service/flag-evaluation/flag_evaluator.go, core/pkg/service/flag-evaluation/flag_evaluator_test.go
fixes #668 
Fixes incorrect error code mapping, which resulted in error message `error code: PROVIDER_NOT_READY: connection not made`
With fix, the error code is set to unknown (as there is no appropriate error code for this error) , and results in message `openfeature: GENERAL: unknown: FLAG_DISABLED`
=> fix: fix connect error code handling for disabled flags

core/pkg/eval/json_evaluator.go, core/pkg/eval/json_evaluator_test.go
Fixes #652 & enhance tests to validate error sates 
Note - had to sync go deps and thus the go mod/sum changes
=> fix: remove disabled flags from bulk evaluation

core/pkg/eval/fractional_evaluation.go, core/pkg/eval/fractional_evaluation_test.go, core/pkg/eval/json_evaluator.go, core/pkg/eval/semver_evaluation.go, core/pkg/eval/semver_evaluation_test.go, core/pkg/eval/string_comparison_evaluation.go, core/pkg/eval/string_comparison_evaluation_test.go, core/pkg/runtime/from_config.go, core/pkg/runtime/from_config_test.go
Is a replacement of https://github.com/open-feature/flagd/pull/684 as GH doesn't allow the reopening of the closed PR (after force push + GH Incident https://www.githubstatus.com/incidents/1g1gkh0qpyvs)
=> chore: refactor json logic evaluator to pass custom operators as options

.github/workflows/release-please.yaml
tar.gz bundling is already handled with widlcard usage `*.tar.gz`. This caused pipeline failures
=> chore: remove duplicate tar.gz bundling

.golangci.yml, flagd/cmd/start_test.go
- replaces `os.Setenv` by `t.Setenv` in unit test (reference: https://pkg.go.dev/testing#T.Setenv)
N/A
=> test(flagd): replace os.Setenv by t.Setenv in test

core/pkg/runtime/from_config.go, core/pkg/service/sync/sync_metrics.go, core/pkg/telemetry/metrics.go
Fixes https://github.com/open-feature/flagd/issues/712 
Refer the following table for metrics renames and their units,
|  Old | New  | Unit |
|---|---|---|
| http_request_duration_seconds  |  http.server.duration | s |
| http_response_size_bytes | http.server.response.size | By |
| http_requests_inflight |http.server.active_requests | {request} |
| impressions | feature_flag.flagd.impression| {impression} | 
| reasons | feature_flag.flagd.evaluation.reason| {reason} |
This change was validated against an OTel setup. Consider following screen captures,
=> feat!: rename metrics and service

.github/workflows/release-please.yaml
- adds Windows binaries to the release
Fixes #775
This issue was introduced when the binary was compressed using zip instead of a tarball.
https://github.com/open-feature/flagd/commit/5060a0e5476038534cc9d2b151cbe48fba78a56d
=> ci: include windows binaries on the release

core/pkg/runtime/from_config.go, core/pkg/runtime/from_config_test.go, core/pkg/sync/http/http_sync.go, docs/configuration/configuration.md
…, in minutes, bet. each HTTP_sync calls
EDIT by @toddbaert : I have modified this PR. I've done a couple things differently than @OsamaNabih :
- interval is in seconds (I think it's likely some people will want sub-minute behavior, and the existing behavior was seconds
- using `sources` for this, as @james-milligan suggested:
- for example: `./bin/flagd start --sources='[{"uri":"https://raw.githubusercontent.com/open-feature/playground/main/config/flagd/flags.json","provider":"http","interval":1}]' --debug` will poll every 1s 
- defaults to 5s to maintain current behavior
- added tests
=> feat: add new configuration "sync-interval" which controls the HTTP polling interval

core/pkg/service/flag-evaluation/flag_evaluator_test.go
- fixes invalid benchmark tests
The benchmark tests started failing after the metadata change.
https://github.com/open-feature/flagd/actions/workflows/publish-benchmark.yaml
`go test -bench=Bench -short -benchtime=5s -benchmem ./core/...`
=> test: fix benchmark tests

.github/workflows/build.yaml
- removes the load tests from the build workflow
This PR removes the load tests job from the build workflow because it causes a long build time and produces inconsistent test results.
The workflow to run a nightly load test remains in place.
=> ci: remove load test from build workflow

web-docs/concepts/architecture.md
- Removes the redundant mermaid diagram (which doesn't render anyway)
- Fixes #801
=> docs: remove architecture diagram

.pre-commit-config.yaml, Makefile
golangci requires go 1.20 now :grimacing: . 
We can upgrade to 1.20, but for now the change in this tool is causing lint failures since we use `@latest` when we install it.
=> chore: pin golangci-lint

Makefile
Closes #853 
This PR fixes the behavior described in the referenced issue by makeing the `test` target in the makefile a `.PHONY`.
The issue was occuring because in the same directory as the Makefile, there was a directory with the same name as the `test` target, which caused the target to not run - For more details, see [this thread](https://stackoverflow.com/questions/3931741/why-does-make-think-the-target-is-up-to-date) on StackOverflow
=> ci: ensure unit tests are run in PR checks

core/pkg/eval/fractional_evaluation.go, core/pkg/eval/fractional_evaluation_test.go, core/pkg/eval/json_evaluator.go, docs/other_resources/in-process-providers/evaluators/fractional_evaluation.md
This PR adds the ability to use nested properties for the bucket key in fractional evaluation. It is a breaking change from the current behaviour. If the bucket key is not provided it will default to `{"cat": [{"var":"$flagd.flagKey"}, {"var":"targetingKey"}]}`.
@toddbaert I am not sure that my approach to the missing bucket key is the best. I would have preferred to add `{"cat": [{"var":"$flagd.flagKey"}, {"var":"targetingKey"}]}` to the targeting object and let JsonLogic handle it, but it would be a bit clumsy and involve string manipulation. I don't think there is a nice way to do it, but I'll play around a bit more.
See #848.
Closes #843.
=> feat: support nested props in fractional evaluator

core/pkg/eval/fractional_evaluation.go, core/pkg/eval/json_evaluator.go, core/pkg/eval/legacy_fractional_evaluation.go, core/pkg/eval/legacy_fractional_evaluation_test.go, core/pkg/eval/semver_evaluation.go, core/pkg/eval/semver_evaluation_test.go, core/pkg/eval/string_comparison_evaluation.go, core/pkg/eval/string_comparison_evaluation_test.go, core/pkg/runtime/from_config.go, docs/configuration/fractional_evaluation.md, web-docs/concepts/index.md
* deprecates fractionalEvaluation in favor of fractional
* adds evaluation names to their implementations to bind them more closely
```
2023-08-28T19:22:53.098-0400    warn    eval/legacy_fractional_evaluation.go:32 fractionalEvaluation is deprecated, please use fractional, see: https://flagd.dev/concepts/#migrating-from-legacy-fractionalevaluation
```
cc @craigpastro 
fixes: https://github.com/open-feature/flagd/issues/871
=> chore: deprecate fractionalEvaluation for fractional

mkdocs.yml, web-docs/ecosystem.md
- Adds a new "ecosystem" page to flagd.dev
- Explains which other tools and projects flagd uses / relies upon
Fixes #875
=> docs: add ecosystem page

.github/workflows/release-please.yaml
- Set the formula path to match the restructured homebrew repo
Fixes #879
=> fix: Set the formula path to match the restructured homebrew repo

.github/workflows/build.yaml, flagd/tests/integration/evaluation_test.go
=> chore: disable caching on integration tests

core/pkg/eval/fractional_evaluation.go, core/pkg/eval/fractional_evaluation_test.go, docs/other_resources/in-process-providers/evaluators/fractional_evaluation.md
Fixes murmur3 hash calculation to be cross language compatible.
See PR discussion here for more details - https://github.com/open-feature/java-sdk-contrib/pull/434
Depends on flagd-testbed PR - https://github.com/open-feature/flagd-testbed/pull/65
=> fix: use 32bit murmur calculation (64 is not stable)

core/pkg/eval/json_evaluator.go
When adding flagdProperties to the context in preparation for evaluation return a new context so that it doesn't affect any references to the current context.
Without this change:
```
$ make run
make run-flagd
cd flagd; go run main.go start -f file:../config/samples/example_flags.flagd.json
______   __       ________   _______    ______      
/_____/\ /_/\     /_______/\ /______/\  /_____/\     
\::::_\/_\:\ \    \::: _  \ \\::::__\/__\:::_ \ \    
\:\/___/\\:\ \    \::(_)  \ \\:\ /____/\\:\ \ \ \   
\:::._\/ \:\ \____\:: __  \ \\:\\_  _\/ \:\ \ \ \  
\:\ \    \:\/___/\\:.\ \  \ \\:\_\ \ \  \:\/.:| | 
\_\/     \_____\/ \__\/\__\/ \_____\/   \____/_/ 
2023-09-18T19:16:39.581-0700    info    cmd/start.go:117        flagd version: dev (HEAD), built at: unknown    {"component": "start"} …
```
=> fix: erroneous warning about prop overwrite

web-docs/deployment.md, web-docs/intro.md
* fills out intro adding some questions.
* not sure if we should add some simple diagrams here
=> chore: adds intro

mkdocs.yml, web-docs/deployment.md
* adds fonticon support
* adds "deployment" page
* I've chosen to specifically add the "in-process" providers here because that's a deployment we've specifically mentioned.. we could add the RPC ones as well in the some other section... not sure about that.
=> chore: deployment

docs/reference/specifications/in-process-providers.md
- remove RPC section from the in-process docs
- addressed various grammatical issues
=> docs: removed RPC section and fixed grammatical issues

docs/architecture.md, docs/faq.md, docs/installation.md, docs/quick-start.md, docs/reference/custom-operations/fractional-operation.md, docs/reference/custom-operations/semver-operation.md, docs/reference/custom-operations/string-comparison-operation.md, docs/reference/flag-definitions.md, docs/reference/monitoring.md, docs/reference/naming.md, docs/reference/specifications/in-process-providers.md, docs/reference/specifications/rpc-providers.md, docs/reference/sync-configuration.md, docs/troubleshooting.md
I was looking into what we could do to improve our indexing and social object graph. I don't think there's much except adding meta-descriptions. These aren't as important as they used to be, but they can still improve indexing and increase likelihood of sharing on social media, etc.
Adding a markdown metadata section with `description` in mkdocs results in it being used in the description meta tag for the page, so I've done that for some pages that are likely to be searched.
=> chore: adds meta descriptions to improve indexing/SEO/etc

docs/reference/specifications/in-process-providers.md
- changes the link to the ecosystem page to use the lowercase name `flagd`
The ecosystem page automatically lowercase the vendor name. This is simply to avoid any unexpected issues in the future.
=> docs: change ecosystem link to use the correct case

release-please-config.json
Attempt to fix release please for mono repo releases
=> fix: add component tag

.github/workflows/release-please.yaml
Remove deprecated command options.
see - https://github.com/google-github-actions/release-please-action#upgrading-from-v3-to-v4
=> fix: remove deprecated command options

docs/reference/flag-definitions.md
- updates examples in the flag definition docs
- addressed some grammatical issues
=> chore: update examples in the flag definitions doc

docs/reference/openfeature-operator/crds/featureflagsource.md
Fix a typo in `docs/featureflagsource.md`
=> docs: fix a typo in `docs/featureflagsource.md`

core/pkg/subscriptions/manager.go
This is a follow up to the latest refactoring PR #1044 to avoid a nil pointer access when attempting to read from a kubernetes sync source
=> fix: make sure sync builder is initialized to avoid nil pointer access

.github/workflows/release-please.yaml
Removes the dependency on native c-libs for more portability.
This is already done in the docker builds, updates were only needed for bins. Tested this locally by mounting it into an old Ubuntu and it resolved the issue.
Fixes: https://github.com/open-feature/flagd/issues/878
=> fix: CGO_ENABLED=0 for statically-linked builds

core/pkg/service/flag-evaluation/connect_service.go
- add custom marshalling options
Fixes #1116
I manually tested to confirm the fix is working. However, it's currently not automatically tested because the issue only affects HTTP-based requests, and the E2E tests use gRPC. I'll create a follow-up task to expand the E2E test suite to include HTTP tests.
=> fix: add custom marshalling options

docs/reference/flagd-cli/flagd_start.md, flagd/cmd/start.go
=> fix: use correct link in sources flag helper text in start cmd

Makefile, docs/schema/v0/flagd-definitions.json, docs/schema/v0/targeting.json
Adds JSON schema at `https://flagd.dev/schema/v0/flagd-definitions.json`, which can be used to add validation to flagd config files.
~Note, to accomplish this cleanly, I have cloned the schemas module twice (at different versions) one is used for json releases (and tagged to something like `json/json-schema-v0.1.2`) while the other is for the protobuf generation and tagged to a release of that. I don't love this, but I think it's needed.~
I've decided against this. I don't think we'll really have conflicts here.
See schema here: https://deploy-preview-1115--polite-licorice-3db33c.netlify.app/schema/v0/flagd-definitions.json
Once this is available, I intend to update a bunch of docs and examples to leverage this schema, and and an blurb in the docs about it.
~Blocked by: …
=> docs: add json-schema

core/pkg/sync/builder/syncbuilder.go, core/pkg/sync/builder/syncbuilder_test.go, core/pkg/sync/builder/utils.go, core/pkg/sync/builder/utils_test.go, core/pkg/sync/http/http_sync.go, core/pkg/sync/http/http_sync_test.go, core/pkg/sync/isync.go, docs/reference/sync-configuration.md
- adds support for any auth scheme in HTTP-sync auth header
Closes #1150
=> feat(core): support any auth scheme in HTTP-sync auth header

renovate.json
Set go version of renovate to 1.20 [1] and avoid updates causing build failures 
[1] - https://docs.renovatebot.com/golang/#go-binary-version
=> chore: fix renovate go version

.github/workflows/release-please.yaml, renovate.json
- reverts release please action to v3 (see [bug](https://github.com/google-github-actions/release-please-action/issues/912)).
- removes GH action SHA pinning
=> chore: revert release-plz version

README.md
The link for "speaks your language" links to a wrong spelling of 'flagd' so make it actually work.
Follow the "speaks your language" link in the "README.md" document.
=> docs: fix a broken search link

netlify.toml
See title. This just allows frontend apps to pull schemas instead of getting blocked by the CO policy.
EDIT:
Tested in the netlify preview and works as expected. Only the `schemas` path is impacted, no CORS on rest of site.
=> docs: relax CO headers for schemas

config/samples/example_flags.flagd.json, docs/architecture.md, docs/index.md, docs/reference/flagd-cli/flagd_start.md, docs/reference/grpc-sync-service.md, flagd/cmd/start.go, flagd/pkg/runtime/from_config.go, flagd/pkg/runtime/runtime.go, flagd/pkg/service/flag-sync/handler.go, flagd/pkg/service/flag-sync/sync-multiplexer.go, flagd/pkg/service/flag-sync/sync-multiplexer_test.go, flagd/pkg/service/flag-sync/sync_service.go, flagd/pkg/service/flag-sync/sync_service_test.go, flagd/pkg/service/flag-sync/util_test.go
Introduce flag sync capability to flagd as discussed at [1] and fixes https://github.com/open-feature/flagd/issues/1230 .
**What's changed ?**
The change included with this PR introduces the gRPC sync contract [2]. This allows flagd to expose its store to in-process provider which consumes gRPC flag stream. 
**How to use ?**
flagd will start sync service on port `8015`. You can alter the default sync port by providing desired port to the startup flag `syncPort` (`--sync-port=8686`) 
**Implementation details**
- Sync service startup is delayed to allow configured flag sources to complete their initial loading (dealy is 5 seconds)
- Sync request's `selector` can be used to specify the specific flag source. If unset, all flags will be sent
- A new stream response will be created whenever …
=> feat: serve sync.proto on port 8015

core/pkg/sync/file/filepath_sync.go, core/pkg/sync/file/filepath_sync_test.go
At the moment, the yamlToJSON will convert `[]byte("")` to `"null"`. While "null" is a normal string, it will bypass all validator and lead to panic.
Fixes [#1242](https://github.com/open-feature/flagd/issues/1242)
I found that sometime, the os.Readfile will return empty byte and no error, this will cause the yamlToJSON convert the rawData ("") to jsonData ("null"). 
Moreover, when I check the log, the watcher is reading file content a lot at a times for checking file changes, so it could be the reason why os.Readfile return empty byte?
I think we have to check the behavior of os.Readfile?
=> fix: occasional panic when watched YAML files change

core/go.mod, core/go.sum, flagd-proxy/go.mod, flagd-proxy/go.sum, flagd/go.sum
Update protobuf dep to address [CVE-2024-24786](https://nvd.nist.gov/vuln/detail/CVE-2024-24786).
=> fix: update protobuff CVE-2024-24786

Makefile, docs/concepts/syncs.md, docs/reference/specifications/protos.md
Remove references to old protos, update `/schemas` submodule.
The old protos were still being used to generate the doc. I've updated them. Also, the `schemas` submodule was set to some very old version, I couldn't even run the live docs for that reason. I've updated it to the latest release of that module.
=> fix: submodules and doc

docs/schema/v0/targeting.json
Update publicly served schema (flagd.dev)
Specifically this supports [enhancements](https://github.com/open-feature/flagd/pull/1266) from @colebaileygit
=> chore: update public schema

flagd/pkg/service/flag-evaluation/connect_service.go, flagd/pkg/service/flag-evaluation/connect_service_test.go, flagd/pkg/service/flag-evaluation/eventing.go, flagd/pkg/service/flag-evaluation/eventing_test.go, flagd/pkg/service/flag-evaluation/flag_evaluator.go, flagd/pkg/service/flag-evaluation/flag_evaluator_v2.go
Before this change the eval services used a unexported
struct which prevented creating eval services outside of
this package.
This change creates a new IEvents interface that allows
providing custom impls of flag eval services.
=> feat: Create interface for eval events. 

core/pkg/evaluator/json.go, core/pkg/service/ofrep/models.go, core/pkg/service/ofrep/models_test.go
- Handle `FlagDisabledErrorCode` and include a specific error message along with general error code 
- Improve error message for targeting rule validation failure
=> feat: improve error log and add flag disabled handling for ofrep

Makefile, flagd/pkg/service/flag-evaluation/ofrep/ofrep_service_test.go
When running the tests locally I noticed that one of them was failing in the `flagd` submodule of the repo. After looking into this, I noticed that the unit tests are only executed for the `core` package in the PR checks - this is fixed with this PR
=> chore: fix unit tests and ensure their execution

core/pkg/telemetry/builder.go, core/pkg/telemetry/metrics.go, core/pkg/telemetry/metrics_test.go, flagd/pkg/runtime/from_config.go, flagd/pkg/service/flag-evaluation/connect_service.go, flagd/pkg/service/flag-evaluation/flag_evaluator.go, flagd/pkg/service/flag-evaluation/flag_evaluator_v2.go, flagd/pkg/service/middleware/metrics/http_metrics.go
Closes #1194
This PR adapts the service setup to not fail when encountering an error in the telemetry setup.
=> chore: adapt telemetry setup error handling

core/pkg/evaluator/json.go, core/pkg/evaluator/json_test.go, core/pkg/model/flag.go, core/pkg/store/flags.go, core/pkg/store/flags_test.go, core/pkg/sync/grpc/grpc_sync.go, core/pkg/sync/isync.go
This change address https://github.com/open-feature/open-feature-operator/issues/664.
**Background**
We allow using multiple flag source CRDs when using flagd-proxy with OFO. Internally, this converts to flagd using gRPC syncs with scopes, where scopes specify the CRD names that need to source flags from. 
**Bug**
We had two bugs, first gRPC resyncs never contained `scope`. This is why we observed `unable to build sync from URI for target` message. Secondly, we triggered resyncs only considering source equility. This is not valid with flagd-proxy as we always go through the proxy for any CRD.
**Fix**
Fix here adds scope to gRPC resyncs and considers both source and selector equality when triggering a resync 
**How to validate the fix**
[Use this …
=> fix: fixes store merge when selector is used

docs/troubleshooting.md, flagd/cmd/root.go
- Observes debug env variable [with or prefix will be `FLAGD_DEBUG`] and binds `--debug` and `-x` flags to it.
Fixes #1323
=> feat: support `FLAGD_DEBUG` / `--debug` / `-x`

core/pkg/service/ofrep/models.go, core/pkg/service/ofrep/models_test.go
This PR improves flagd bulk evaluation empty response by adding required `flags` property. 
Related - https://github.com/open-feature/protocol/pull/27
=> feat: add mandatory flags property in bulk response

core/pkg/evaluator/fractional.go, core/pkg/evaluator/fractional_test.go, docs/reference/custom-operations/fractional-operation.md, docs/reference/specifications/custom-operations/fractional-operation-spec.md
Closes #1282 
This PR adds support for using relative weights instead of percentages that need to add up to 100.
The behavior for existing flag configs does not change with this PR, so those will continue to work as they did previously
=> feat: support relative weighting for fractional evaluation

core/pkg/evaluator/fractional.go, core/pkg/evaluator/ievaluator.go, core/pkg/evaluator/json.go, core/pkg/evaluator/json_test.go, core/pkg/evaluator/mock/ievaluator.go, core/pkg/service/ofrep/models.go, core/pkg/store/flags.go, flagd/pkg/service/flag-evaluation/flag_evaluator.go, flagd/pkg/service/flag-evaluation/flag_evaluator_test.go, flagd/pkg/service/flag-evaluation/flag_evaluator_v2.go, flagd/pkg/service/flag-evaluation/flag_evaluator_v2_test.go, flagd/pkg/service/flag-evaluation/ofrep/handler.go, flagd/pkg/service/flag-evaluation/ofrep/handler_test.go, flagd/pkg/service/flag-evaluation/ofrep/ofrep_service_test.go, flagd/pkg/service/flag-sync/sync-multiplexer.go
Fixes #1328
flagd's core components are intended to be reused. This PR change the`IStore` interface by allowing an error to be returned from `GetAll`.  This error is then propagated through `ResolveAllValues`. This change enables custom `IStore` implementations to return errors and propagate them through the resolver layer.
With this change, I have upgrade OFREP bulk evaluator and flagd RPC  `ResolveAll` with error propagation.
OFREP - Log warning with resolver error and return HTTP 500 with a tracking reference
RPC - Log warning with resolver error and return an error with a tracking reference
=> feat!: support emitting errors from the bulk evaluator

flagd/pkg/service/flag-sync/sync-multiplexer.go, flagd/pkg/service/flag-sync/sync-multiplexer_test.go, flagd/pkg/service/flag-sync/sync_service_test.go, flagd/pkg/service/flag-sync/util_test.go
Fixes an issue where invalid flag payloads were returned on sync requests with scopes if the flag set was empty.
Below is an example of the bug.
```shell
$ grpcurl -import-path /home/todd/temp -proto sync.proto -plaintext localhost:8015 flagd.sync.v1.FlagSyncService/FetchAllFlags
{
"flagConfiguration": "{\"flags\":{}}"
}
$ grpcurl -import-path /home/todd/temp -proto sync.proto -plaintext -d '{"selector":"../config/samples/example_flags.flagd.json"}' localhost:8015 flagd.sync.v1.FlagSyncService/FetchAllFlags 
{}
```
=> fix: invalid scoped-sync responses for empty flags

core/pkg/sync/builder/syncbuilder.go, core/pkg/sync/builder/syncbuilder_test.go, core/pkg/sync/grpc/grpc_sync.go, core/pkg/sync/grpc/grpc_sync_test.go, core/pkg/sync/isync.go, docs/reference/sync-configuration.md
Added a new config option `maxMsgSize` which will
allow users to override default message size 4Mb.
- allow override default max message size 4Mb
Fixes #1357 
To test this feature you need a flag source with large number of flags > 4Mb, e.g. below we are running with max size of 5Mb+
```
./flagd start --port 8013 --sync-port 8017 --sources='[{"uri": "localhost:8015", "provider": "grpc", "tls": false, "providerID": "flagd-sidecar", "selector": "all-flags", "maxMsgSize": 5728474}]'
______   __       ________   _______    ______
/_____/\ /_/\     /_______/\ /______/\  /_____/\
\::::_\/_\:\ \    \::: _  \ \\::::__\/__\:::_ \ \
\:\/___/\\:\ \    \::(_)  \ \\:\ /____/\\:\ \ \ \
\:::._\/ \:\ \____\:: __  \ \\:\\_  _\/ \:\ \ \ \
\:\ \    \:\/___/\\:.\ \  \ \\:\_\ \ \  \:\/.:| |
\_\/     \_____\/ …
```
=> feat: added new grpc sync config option to allow setting max receive message size.

docs/reference/monitoring.md
update flagd otel example configurations. Specially, removing deprecated entries and upgrading to match changes of jaeger [1]
[1] - https://opentelemetry.io/blog/2023/jaeger-exporter-collector-migration/
=> chore: update otel example configurations

docs/reference/openfeature-operator/overview.md
Fixes a typo in `docs/reference/openfeature-operator/overview.md`
=> docs: fix typo

.github/workflows/build.yaml
A similar change was main in OFO to address the same issue.
https://github.com/open-feature/open-feature-operator/pull/713
=> ci: fix security scan input path

.github/workflows/release-please.yaml
- avoids running the license bundling command if the directory doesn't exist.
Resolves publishing errors like this.
https://github.com/open-feature/flagd/actions/runs/11561455616/job/32180508181
=> ci: fix license bundling command

.github/workflows/build.yaml, test/integration/config/envoy.yaml, test/integration/evaluation_test.go, test/integration/go.mod, test/integration/json_evaluator_test.go
Added custom gRPC resolver e2e test
- added custom resolver e2e test coverage
https://github.com/open-feature/go-sdk-contrib/issues/585
=> test: update e2e tests

docs/reference/flag-definitions.md, docs/reference/specifications/providers.md
- adds docs about flag metadata and merging
=> docs: flag and flag-set metadata

core/pkg/store/flags.go, flagd/pkg/service/flag-sync/sync-multiplexer.go, flagd/pkg/service/flag-sync/sync-multiplexer_test.go, flagd/pkg/service/flag-sync/util_test.go
This PR fixes an issue where the wrong metadata is returned when a selector is used.
This bug is easy to fix, but was also easy to write. We eventually need to refactor the flag memory store (`flags.go`) to store all flags per source. This was retrofitted in to support selectors, from a single-flagSet model.
To test, do the manual test specified in https://github.com/open-feature/flagd/issues/1597.
Fixes: https://github.com/open-feature/flagd/issues/1597
=> fix: incorrect metadata returned per source

CODEOWNERS
global maintainers approvals etc should have the same effect as the one of the flagd maintainers
=> chore: add global maintainers to the codeowners

mkdocs.yml
- I noticed the URLs generated in the content tab were not that appealing. This ensures they follow a consistent pattern and are more user-friendly
Follows on from #1626
=> docs: improve content tab anchors on getting started

core/pkg/telemetry/builder.go
- removed the 2 second hardcoded metric export interval
- use OTel default 60 second metric export interval
- the export interval can be overridden via the env var `OTEL_METRIC_EXPORT_INTERVAL`
Fixes #1603 
Removing the hardcoded value will allow users to override the default interval via environment variables.
This 
- https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric#WithInterval
- https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/sdk-environment-variables.md#periodic-exporting-metricreader
=> refactor: removed hardcoded metric export interval and use otel default

core/pkg/service/iservice.go, docs/reference/flagd-cli/flagd_start.md, flagd/cmd/start.go, flagd/pkg/runtime/from_config.go, flagd/pkg/service/flag-evaluation/connect_service.go, flagd/pkg/service/flag-evaluation/flag_evaluator_v2.go, flagd/pkg/service/flag-evaluation/flag_evaluator_v2_test.go, flagd/pkg/service/flag-sync/handler.go, flagd/pkg/service/flag-sync/sync_service.go, flagd/pkg/service/flag-sync/sync_service_test.go
- adds server side deadline for sync and event streams configurable via cmd argument `--stream-deadline`
#1582
1. Run flagd with `--stream-deadline 3s` // 3s can be replaced with any duration the deadline should have
2. Test Event Stream deadline: run `grpcurl -v --proto schemas/protobuf/flagd/evaluation/v1/evaluation.proto -plaintext localhost:8013 flagd.evaluation.v1.Service/EventStream` or similar depending on your flagd settings to check if the deadline exceeded is returned after the specified duration
3. Test Sync Service Stream deadline: run `grpcurl -v --proto schemas/protobuf/flagd/sync/v1/sync.proto -plaintext localhost:8015 flagd.sync.v1.FlagSyncService/SyncFlags` or similar depending on your flagd settings to check if the deadline exceeded is returned after the specified …
=> feat: add server-side deadline to sync service

docs/architecture-decisions/flag-configuration.md
Another "retrospective" ADR, like the cucumber one.
This explains our JSONLogic choice, shared `$evaluators`, as well as the the semantics of flagd's use of OpenFeature's [resolution reasons](https://openfeature.dev/specification/types#resolution-reason).
=> docs: add flag config adr

docs/architecture-decisions/multiple-flag-set-support.md
The goal of this decision document is to establish flag sets as a first class concept in `flagd`, and support the dynamic addition/update/removal of flag sets at runtime.
See document for all justifications and background.
@dominikhaska @tangenti @cupofcat 
Alternative proposal here: https://github.com/open-feature/flagd/pull/1644#discussion_r2149723952
=> docs(ADR): propose support for flag set selection

core/pkg/evaluator/json.go, core/pkg/evaluator/legacy_fractional_test.go
This makes the RPC mode consistent with our in-process evaluations when a variant is returned from targeting which is not in the variants list.
Relates to https://github.com/open-feature/flagd-testbed/commit/758fbd5b84731c1a96dbd186484c46d3b8f746ed
=> fix: general err if targeting variant not in variants

CONTRIBUTING.md, core/pkg/sync/file/filepath_sync_test.go, core/pkg/sync/http/http_sync_test.go
Adds back a test that was inappropriately removed (as explained [here](https://github.com/beeme1mr/flagd/pull/16/files#r2223712589)).
Also fixes some typos.
=> chore: add back file-delete test

core/pkg/evaluator/json_test.go, core/pkg/model/flag.go, core/pkg/notifications/notifications.go, core/pkg/store/store.go
This pull request removes the unused `Selector` field from the `Flag` struct and deletes the `SourceDetails` struct, which is no longer in use.
These changes are part of a cleanup effort following the major refactoring in PR #1702, which made these components obsolete.
Follow-up to #1702
All existing tests should continue to pass.
=> refactor: removed unused Selector from Flag and Store.
